name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Web Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Build Web Client
        working-directory: ./client
        run: npm run build

      - name: Setup Firebase Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./client/firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT}}

      - name: Deploy to Firebase
        working-directory: ./client
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./firebase-service-account.json
