name: Run Client E2E Test Suite on PR

on:
    pull_request:
        branches:
            - main

jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install Dependencies
              run: |
                cd client
                npm install

            - name: Start React Development Server
              # "&" puts process in background
              run: |
                cd client
                npm start &
                echo "ReactAppPID=$!" >> $GITHUB_ENV

            - name: Wait for React Development Server to Start
              run: npm i -g wait-on && wait-on http://localhost:3000

            - name: Run E2E Test Suite
              run: |
                cd client
                npx cypress run

            - name: Stop React Development Server
              if: always()
              run: |
                kill $ReactAppPID
