name: Run E2E Tests and Publish to Preview Site

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm i

      - name: Start React Development Server
        # "&" puts process in background
        run: npm start &
          echo "ReactAppPID=$!" >> $GITHUB_ENV

      - name: Wait for React Development Server to Start
        run: npm i -g wait-on && wait-on http://localhost:3000

      - name: Run E2E Test Suite
        run: npx cypress run

      - name: Stop React Development Server
        if: always()
        run: |
          kill $ReactAppPID

  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GENERATION_FINDER }}'
          projectId: generation-finder
